# Generated by Django 3.0.6 on 2020-05-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200528_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='purchased_products',
        ),
    ]
